version: "3"

services:
  blue:
    build: ./app
    container_name: blue_app
    ports:
      - "3001:3000"
    environment:
      - ENVIRONMENT=blue

  green:
    build: ./app
    container_name: green_app
    ports:
      - "3002:3000"
    environment:
      - ENVIRONMENT=green

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf